# Generated by Django 4.0.1 on 2022-03-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'permissions': (('can_add_money', 'top_add_balance'),), 'verbose_name': 'Wallet', 'verbose_name_plural': 'Wallets'},
        ),
    ]
