# Generated by Django 4.0.1 on 2022-02-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_day',
            field=models.DateField(max_length=255, null=True, verbose_name='Birth day'),
        ),
    ]
