# Generated by Django 4.0.1 on 2022-03-22 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_wallet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'permissions': (('can_add_money', 'Top add balance'),), 'verbose_name': 'Wallet', 'verbose_name_plural': 'Wallets'},
        ),
    ]
