# Generated by Django 4.0.1 on 2022-02-20 20:50

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='static_avatar',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.get_path, verbose_name='Avatar'),
        ),
    ]
