# Generated by Django 4.0.1 on 2022-03-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_profile_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
        migrations.AlterModelTable(
            name='wallet',
            table=None,
        ),
    ]
