# Generated by Django 4.0.1 on 2022-03-11 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Product type')),
            ],
            options={
                'verbose_name': 'Product type',
                'verbose_name_plural': 'Product types',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('manufacturer_name', models.CharField(max_length=255, verbose_name='manufacturer name')),
                ('discount', models.FloatField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='', verbose_name='Product photo')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.producttype')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_refresh_rate_hertz', models.IntegerField(verbose_name='Screen_refresh_rate_hertz')),
                ('screen_size', models.FloatField(verbose_name='Screen size')),
                ('screen_resolution', models.CharField(max_length=255, verbose_name='screen_resolution')),
                ('screen_matrix', models.CharField(max_length=255, verbose_name='Screen matrix')),
                ('CPU', models.CharField(max_length=255, verbose_name='CPU')),
                ('ram_in_gigabytes', models.IntegerField(verbose_name='RAM in gigabytes')),
                ('Weight', models.FloatField(verbose_name='Weight in kilograms')),
                ('operating_system', models.CharField(max_length=255, verbose_name='Operating system')),
                ('battery_capacity_in_milliamps', models.IntegerField(verbose_name='battery capacity in milliamps')),
                ('built_in_memory_in_gigabytes', models.IntegerField(verbose_name='Built-in memory in gigabytes')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('number_of_camera', models.IntegerField(verbose_name='number of camera')),
                ('number_of_SIM_cards', models.IntegerField(verbose_name='Number of SIM cards')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'MobilePhone',
                'verbose_name_plural': 'MobilePhones',
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_refresh_rate_hertz', models.IntegerField(verbose_name='Screen_refresh_rate_hertz')),
                ('screen_size', models.FloatField(verbose_name='Screen size')),
                ('screen_resolution', models.CharField(max_length=255, verbose_name='screen_resolution')),
                ('screen_matrix', models.CharField(max_length=255, verbose_name='Screen matrix')),
                ('CPU', models.CharField(max_length=255, verbose_name='CPU')),
                ('ram_in_gigabytes', models.IntegerField(verbose_name='RAM in gigabytes')),
                ('Weight', models.FloatField(verbose_name='Weight in kilograms')),
                ('operating_system', models.CharField(max_length=255, verbose_name='Operating system')),
                ('battery_capacity_in_milliamps', models.IntegerField(verbose_name='battery capacity in milliamps')),
                ('built_in_memory_in_gigabytes', models.IntegerField(verbose_name='Built-in memory in gigabytes')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('number_of_ram_slots', models.IntegerField(verbose_name='Number_of_RAM_slots')),
                ('video_card_type', models.CharField(max_length=255, verbose_name='Video card type')),
                ('video_processor', models.CharField(max_length=255, verbose_name='video processor')),
                ('memory_storage_type', models.CharField(max_length=255, verbose_name='memory storage type')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'Laptop',
                'verbose_name_plural': 'Laptops',
            },
        ),
    ]
