# Generated by Django 4.0.1 on 2022-03-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Product type', 'verbose_name_plural': 'Product types'},
        ),
    ]
