# Generated by Django 4.0.1 on 2022-05-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity in stock'),
            preserve_default=False,
        ),
    ]
