# Generated by Django 4.0.1 on 2022-07-16 18:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_product', models.PositiveIntegerField(verbose_name='Total products')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=9)], verbose_name='Total price')),
                ('in_order', models.BooleanField(default=False)),
                ('for_anonymous_user', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Basket',
                'verbose_name_plural': 'Baskets',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name="Buyer's name")),
                ('last_name', models.CharField(max_length=255, verbose_name="Buyer's last name")),
                ('phone', models.CharField(max_length=20, verbose_name="Buyer's phone number")),
                ('address', models.CharField(blank=True, max_length=1024, null=True, verbose_name="buyer's address")),
                ('status', models.CharField(choices=[('new', 'New order'), ('in_progress', 'Order in processing'), ('is_ready', 'Order is ready'), ('completed', 'Order completed')], default='new', max_length=100, verbose_name='Order status')),
                ('buying_type', models.CharField(choices=[('self', 'Pickup'), ('delivery', 'Delivery')], default='self', max_length=100, verbose_name='Order type')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment to the order')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Order creation date')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date of receipt of the order')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.basket', verbose_name='Basket')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='BasketItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(limit_value=10, message='You cannot buy more than 10 copies of the same product in 1 order'), django.core.validators.MinValueValidator(limit_value=1, message='You cannot buy less than one copy')], verbose_name='Quantity product')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Total price')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.basket', verbose_name='Basket')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.profile')),
            ],
            options={
                'verbose_name': 'Basket item',
                'verbose_name_plural': 'Basket items',
            },
        ),
        migrations.AddField(
            model_name='basket',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='related_basket', to='order.BasketItems'),
        ),
        migrations.AddField(
            model_name='basket',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.profile'),
        ),
    ]
