# Generated by Django 4.0.1 on 2022-03-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Basket', 'verbose_name_plural': 'Baskets'},
        ),
        migrations.AlterModelOptions(
            name='basketitems',
            options={'verbose_name': 'Basket item', 'verbose_name_plural': 'Basket items'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name': 'Order item', 'verbose_name_plural': 'Order items'},
        ),
    ]
