# Generated by Django 4.0.1 on 2022-08-09 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='total_price',
        ),
        migrations.AddField(
            model_name='basket',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=9)], verbose_name='Final price'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='total_product',
            field=models.PositiveIntegerField(default=0, verbose_name='Total products'),
        ),
    ]
