# Generated by Django 4.0.1 on 2022-08-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_basket_total_price_basket_final_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketitems',
            old_name='profile',
            new_name='user',
        ),
    ]
