# Generated by Django 4.0.1 on 2022-08-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_profile_basketitems_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitems',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity product'),
        ),
    ]
