# Generated by Django 4.0.1 on 2022-08-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_basketitems_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Final price'),
        ),
    ]
